const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    signout: "Sign Out",
    homepage: "Homepage",
    gptSearch: "GPT Search",
    trending: "Trending",
    nowPlaying: "Now Playing",
    popular: "Popular",
    upcomingMovies: "Upcoming Movies",
    horror: "Horror",
    signin: "Sign In",
    signup: "Sign Up",
    fullName: "Full Name",
    emailOrMobileNumber: "Email Or mobile Number",
    password: "Password",
    alreadyRegistered: "Already Registered? Sign In Now.",
    newToNetflix: "New to Netflix? Sign Up Now.",
    play: "Play",
    moreInfo: "More Info",
    movieTitle: "Moana 2",
    movieDescription:
      "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    signout: "साइन आउट",
    homepage: "मुखपृष्ठ",
    gptSearch: "जीपीटी खोज",
    trending: "रुझान",
    nowPlaying: "अभी फिल्में चल रही हैं",
    popular: "लोकप्रिय",
    upcomingMovies: "आने वाली फिल्में",
    horror: "डरावनी",
    signin: "दाखिल करना",
    signup: "साइन अप करें",
    fullName: "पूरा नाम",
    emailOrMobileNumber: "ईमेल या मोबाइल नंबर",
    password: "पासवर्ड",
    alreadyRegistered: "पहले से ही पंजीकृत? अब साइन इन करो।",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? अभी साइनअप करें।",
    play: "प्ले",
    moreInfo: "और जानकारी",
    movieTitle: "मोआना 2",
    movieDescription:
      "अपने रास्ते खोजने वाले पूर्वजों से एक अप्रत्याशित कॉल प्राप्त करने के बाद, मोआना माउई और एक नए दल के साथ ओशिनिया के सुदूर समुद्र और खतरनाक, लंबे समय से खोए हुए पानी में एक साहसिक कार्य के लिए यात्रा करती है, जिसका उसने पहले कभी सामना नहीं किया था।",
  },
  punjabi: {
    search: "ਖੋਜ",
    gptSearchPlaceholder: "ਤੁਸੀਂ ਅੱਜ ਕੀ ਦੇਖਣਾ ਚਾਹੋਗੇ?",
    signout: "ਸਾਇਨ ਆਉਟ",
    homepage: "ਹੋਮਪੇਜ",
    gptSearch: "GPT ਖੋਜ",
    trending: "ਪ੍ਰਚਲਿਤ",
    nowPlaying: "ਹੁਣ ਚੱਲ ਰਿਹਾ ਹੈ",
    popular: "ਪ੍ਰਸਿੱਧ",
    upcomingMovies: "ਆਗਾਮੀ ਫਿਲਮਾਂ",
    horror: "ਦਹਿਸ਼ਤ",
    signin: "ਸਾਈਨ - ਇਨ",
    signup: "ਸਾਇਨ ਅਪ",
    fullName: "ਪੂਰਾ ਨਾਂਮ",
    emailOrMobileNumber: "ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ",
    password: "ਪਾਸਵਰਡ",
    alreadyRegistered: "ਕੀ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ? ਹੁਣੇ ਸਾਈਨ ਇਨ ਕਰੋ।",
    newToNetflix: "Netflix ਲਈ ਨਵੇਂ? ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ।",
    play: "ਖੇਡੋ",
    moreInfo: "ਹੋਰ ਜਾਣਕਾਰੀ",
    movieTitle: "ਮੋਨਾ ੨",
    movieDescription:
      "ਆਪਣੇ ਰਾਹ ਲੱਭਣ ਵਾਲੇ ਪੂਰਵਜਾਂ ਤੋਂ ਇੱਕ ਅਚਾਨਕ ਕਾਲ ਪ੍ਰਾਪਤ ਕਰਨ ਤੋਂ ਬਾਅਦ, ਮੋਆਨਾ ਮਾਉਈ ਅਤੇ ਇੱਕ ਨਵੇਂ ਚਾਲਕ ਦਲ ਦੇ ਨਾਲ ਓਸ਼ੇਨੀਆ ਦੇ ਦੂਰ ਸਮੁੰਦਰਾਂ ਵਿੱਚ ਅਤੇ ਖਤਰਨਾਕ, ਲੰਬੇ ਸਮੇਂ ਤੋਂ ਗੁੰਮ ਹੋਏ ਪਾਣੀਆਂ ਵਿੱਚ ਇੱਕ ਸਾਹਸ ਲਈ ਯਾਤਰਾ ਕਰਦੀ ਹੈ ਜਿਸਦਾ ਉਸਨੇ ਕਦੇ ਸਾਹਮਣਾ ਕੀਤਾ ਹੈ।",
  },
  telugu: {
    search: "శోధించండి",
    gptSearchPlaceholder: "మీరు ఈరోజు ఏమి చూడాలనుకుంటున్నారు?",
    signout: "సైన్ అవుట్ చేయండి",
    homepage: "హోమ్‌పేజీ",
    gptSearch: "GPT శోధన",
    trending: "ట్రెండింగ్‌లో ఉంది",
    nowPlaying: "ఇప్పుడు ప్లే అవుతోంది",
    popular: "జనాదరణ పొందినది",
    upcomingMovies: "రాబోయే సినిమాలు",
    horror: "భయానక",
    signin: "సైన్ ఇన్ చేయండి",
    signup: "సైన్ అప్ చేయండి",
    fullName: "పూర్తి పేరు",
    emailOrMobileNumber: "ఇమెయిల్ లేదా మొబైల్ నంబర్",
    password: "పాస్వర్డ్",
    alreadyRegistered: "ఇప్పటికే నమోదు చేయబడిందా? ఇప్పుడే సైన్ ఇన్ చేయండి.",
    newToNetflix: "Netflixకి కొత్తవా? ఇప్పుడే సైన్ అప్ చేయండి. ",
    play: "ఆడండి",
    moreInfo: "మరింత సమాచారం",
    movieTitle: "మోనా 2",
    movieDescription:
      "ఆమె దారిచూపే పూర్వీకుల నుండి ఊహించని కాల్ అందుకున్న తర్వాత, మోయానా మౌయి మరియు కొత్త సిబ్బందితో కలిసి ఓషియానియాలోని సుదూర సముద్రాలకు మరియు ప్రమాదకరమైన, దీర్ఘకాలంగా కోల్పోయిన జలాల్లోకి ఆమె ఎప్పుడూ ఎదుర్కొన్న సాహసం కోసం ప్రయాణిస్తుంది.",
  },
  marathi: {
    search: "शोधा",
    gptSearchPlaceholder: "तुम्हाला आज काय बघायला आवडेल?",
    signout: "साइन आउट करा",
    homepage: "मुखपृष्ठ",
    gptSearch: "GPT शोध",
    trending: "ट्रेंडिंग",
    nowPlaying: "आता खेळत आहे",
    popular: "लोकप्रिय",
    upcomingMovies: "आगामी चित्रपट",
    horror: "भयपट",
    signin: "साइन इन करा",
    signup: "साइन अप करा",
    fullName: "पूर्ण नाव",
    emailOrMobileNumber: "ईमेल किंवा मोबाईल नंबर",
    password: "पासवर्ड",
    alreadyRegistered: "आधीच नोंदणीकृत? आता साइन इन करा.",
    newToNetflix: "Netflix वर नवीन? आता साइन अप करा.",
    play: "खेळणे",
    moreInfo: "अधिक माहिती",
    movieTitle: "मोआना २",
    movieDescription:
      "तिच्या मार्ग शोधणाऱ्या पूर्वजांकडून अनपेक्षित कॉल मिळाल्यानंतर, मोआना माउई आणि नवीन क्रू सोबत ओशिनियाच्या सुदूर समुद्रापर्यंत आणि धोकादायक, लांब हरवलेल्या पाण्यात प्रवास करते आणि तिला कधीही सामना करावा लागला नसलेल्या साहसासाठी.",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    signout: "Desconectar",
    homepage: "Página principal",
    gptSearch: "Búsqueda GPT",
    trending: "Tendencia",
    nowPlaying: "Ahora jugando",
    popular: "Popular",
    upcomingMovies: "Próximas películas",
    horror: "Horror",
    signin: "Iniciar sesión",
    signup: "Inscribirse",
    fullName: "Nombre completo",
    emailOrMobileNumber: "Correo electrónico o número de móvil",
    password: "Contraseña",
    alreadyRegistered: "¿Ya estás registrado? Inicia sesión ahora.",
    newToNetflix: "¿Nuevo en Netflix? Regístrese ahora.",
    play: "jugar",
    moreInfo: "más información",
    movieTitle: "moana 2",
    movieDescription:
      "Después de recibir una llamada inesperada de sus ancestros buscadores de caminos, Moana viaja junto a Maui y una nueva tripulación a los lejanos mares de Oceanía y a aguas peligrosas y perdidas hace mucho tiempo para vivir una aventura como nunca antes había enfrentado.",
  },
  french: {
    search: "Recherche",
    gptSearchPlaceholder: "Qu’aimeriez-vous regarder aujourd’hui ?",
    signout: "Se déconnecter",
    homepage: "Page d'accueil",
    gptSearch: "Recherche GPT",
    trending: "Tendance",
    nowPlaying: "Lecture en cours",
    popular: "Populaire",
    upcomingMovies: "Films à venir",
    horror: "Horreur",
    signin: "Se connecter",
    signup: "S'inscrire ",
    fullName: "Nombre completo",
    emailOrMobileNumber: "Email ou numéro de portable",
    password: "Mot de passe",
    alreadyRegistered: "Déjà inscrit ? Connectez-vous maintenant.",
    newToNetflix: "Nouveau sur Netflix ? Inscrivez-vous maintenant.",
    play: "jouer",
    moreInfo: "plus d'infos",
    movieTitle: "Moana 2",
    movieDescription:
      "Après avoir reçu un appel inattendu de ses ancêtres, Moana voyage aux côtés de Maui et d'un nouvel équipage vers les mers lointaines d'Océanie et dans des eaux dangereuses et perdues depuis longtemps pour une aventure sans précédent.",
  },
  chinese: {
    search: "搜索",
    gptSearchPlaceholder: "今天你想看什么？",
    signout: "登出",
    homepage: "主页",
    gptSearch: "GPT 搜索",
    trending: "流行趋势",
    nowPlaying: "正在播放",
    popular: "受欢迎的",
    upcomingMovies: "即将上映的电影",
    horror: "恐怖",
    signin: "登入",
    signup: "报名",
    fullName: "姓名",
    emailOrMobileNumber: "电子邮件或手机号码",
    password: "密码",
    alreadyRegistered: "已经注册？立即登录。",
    newToNetflix: "刚接触 Netflix？立即注册。",
    play: "玩",
    moreInfo: "更多信息",
    movieTitle: "海洋奇缘2",
    movieDescription:
      "在接到寻路祖先的意外电话后，莫阿娜与毛伊岛和新船员一起前往大洋洲的远海，进入危险、失落已久的水域，开始一场她从未遇到过的冒险。",
  },
  portuguese: {
    search: "Procurar",
    gptSearchPlaceholder: "O que você gostaria de assistir hoje?",
    signout: "Sair",
    homepage: "Página inicial",
    gptSearch: "Pesquisa GPT",
    trending: "Tendências",
    nowPlaying: "Agora jogando",
    popular: "Popular",
    upcomingMovies: "Próximos filmes",
    horror: "Horror",
    signin: "Entrar",
    signup: "Inscrever-se",
    fullName: "Nome completo",
    emailOrMobileNumber: "E-mail ou número de celular",
    password: "Senha",
    alreadyRegistered: "Já está cadastrado? Faça login agora.",
    newToNetflix: "Novo no Netflix? Inscreva-se agora.",
    play: "jogar",
    moreInfo: "mais informações",
    movieTitle: "Moana 2",
    movieDescription:
      "Depois de receber um telefonema inesperado de seus ancestrais, Moana viaja ao lado de Maui e uma nova tripulação para os mares distantes da Oceania e para águas perigosas e há muito perdidas para uma aventura diferente de tudo que ela já enfrentou.",
  },
  urdu: {
    search: "تلاش کریں۔",
    gptSearchPlaceholder: "آج آپ کیا دیکھنا چاہیں گے؟",
    signout: "سائن آؤٹ کریں۔",
    homepage: "ہوم پیج",
    gptSearch: "GPT تلاش",
    trending: "ٹرینڈنگ",
    nowPlaying: "اب چل رہا ہے۔",
    popular: "مقبول",
    upcomingMovies: "آنے والی فلمیں",
    horror: "وحشت",
    signin: "سائن ان کریں۔",
    signup: "سائن اپ کریں۔",
    fullName: "پورا نام",
    emailOrMobileNumber: "ای میل یا موبائل نمبر",
    password: "پاس ورڈ",
    alreadyRegistered: "پہلے سے رجسٹرڈ ہے؟ ابھی سائن ان کریں۔",
    newToNetflix: "Netflix میں نئے ہیں؟ ابھی سائن اپ کریں۔",
    play: "کھیلیں",
    moreInfo: "مزید معلومات",
    movieTitle: "موانا 2",
    movieDescription:
      "اپنے راستے تلاش کرنے والے آباؤ اجداد کی طرف سے ایک غیر متوقع کال موصول ہونے کے بعد، موانا ماوئی اور ایک نئے عملے کے ساتھ اوشیانا کے دور سمندروں تک اور خطرناک، طویل کھوئے ہوئے پانیوں میں ایک مہم جوئی کے لیے سفر کرتی ہے جس کا اسے کبھی سامنا نہیں کرنا پڑا۔",
  },
};

export default lang;
